PhuongCaradoc209/Project_OOP_FishingGame

- src/main/GamePanel.java
> Expain the screen window

- src/main/GamePanel.java
- src/main/KeyHandler.java
- src/main/UI.java
Add gameState. Draw tittleScreen and selectCharacterScreen in UI class. Set up gameState in KeyHandler
> Add gameState. Draw tittleScreen and selectCharacterScreen in UI class. Set up gameState in KeyHandler

- src/entity/Player.java
- src/main/KeyHandler.java
Add select character screen after player choose start game in tittle screen. Fix bug can not get the character images after choosing character.
> Add selectCharacterScreen. Fix error can not display player on screen

- src/entity/Player.java
Add function for player: player can not move if at edge of map. Add checking tile collision for player. Set up the solid Area for player
> Add function for player. Add checking tile collision for player. Set up the solid Area for player

- src/main/GamePanel.java
- src/main/KeyHandler.java
- src/main/Sound.java
Create a class Sound to set up sound. Add sound for select and click when choosing options in tittle screen and character screen. Add background sound for game in playState.
> Add and set up sounds for game

- .idea/misc.xml
- src/entity/Animal_Duck.java
- src/entity/Entity.java
- src/entity/Player.java
- src/main/AssetSetter.java
- src/main/CollisionChecker.java
- src/main/GamePanel.java
Add duck on map. Setting duck moving and upgrade Entity class, CollisionChecker class for duck
> Add animal: duck on map

- .idea/misc.xml
- src/entity/Animal_Cow.java
- src/main/AssetSetter.java
Cow plays a role as providing milk for player. Hence, player can drink it and recover the physical
> Add cow for game. Also display gesture for cow

- src/entity/Animal_Duck.java
- src/main/AssetSetter.java
Fix bug of duck (always moving right side) and set its coordinate on the map
> Fix bug of duck (always moving right side) and set its coordinate on the map

- src/entity/Player.java
- src/main/UI.java
[This autoDisplayState help display a small dialog icon automatically when near the target]
> Add autoDisplayState for game. Add 2 small dialog icon: for cow and for npc

- src/entity/Player.java
When player walking on grass, the sound of grass will be displayed
> Add sound when player walking on grass (setTileSound method)

- src/entity/Animal_Duck.java
- src/entity/Player.java
- src/main/AssetSetter.java
- src/main/CollisionChecker.java
Bugs: Cow disappear when pressing Enter, Duck can go ashore at a specified position
> Fix bugs of Cow and Duck

- src/entity/Player.java
- src/main/EventHandler.java
- src/main/EventRect.java
- src/main/GamePanel.java
- src/main/UI.java
- src/object/OBJ_PHYSICAL.java
Include 3 new classes:
EventHandler - manages events react such as decrease or increase player's physical 
EventRect - plays a role as a specified event's position on map 
OBJ_PHYSICAL - load physical image
> Add physical status for player

- src/entity/Animal_Duck.java
- src/main/AssetSetter.java
- src/main/CollisionChecker.java
The bug is that in specified position, player can go through the wall
> Fix again collision Tile of duck and player

- src/main/EventHandler.java
- src/main/KeyHandler.java
- src/main/UI.java
Fishing bar is the gameplay that allow player can catch fish draw
Notification plays a role as throws notifications
> Add fishing gameplay (fishing bar) and drawNotification on screen

- .idea/misc.xml
- src/main/KeyHandler.java
- src/main/UI.java
This menu allow player can:
- Set up volume of music and sound effect.
- Learn about shortcut of control
- Out the game and return to the tittle screen
> Update menu and control for game.

- src/entity/NPC_OldMan.java
- src/entity/Player.java
- src/object/OBJ_FishingRod1.java
- src/object/OBJ_FishingRod2.java
- src/object/OBJ_FishingRod3.java
- src/object/OBJ_Grass.java
Adding npc inventory and player inventory and update trade system to remove old fishing rod after upgrade a new one
> Update trade system for NPC_OldMan.java

- src/entity/Player.java
- src/main/KeyHandler.java
- src/main/UI.java
> Add the current fishing rod status and the player's current coin to the screen.

- src/Environment/DayNight.java
- src/Environment/EnvironmentManager.java
- src/main/GamePanel.java
At this moment, day and night status just for beauty
> Update day and night status for game

- src/entity/Entity.java
- src/entity/Player.java
- src/main/GamePanel.java
- src/main/KeyHandler.java
- src/main/UI.java
Setting how to convert to the other map by transitionState. Then draw the fishTank map. Setting key "L" to convert to fishTank map. Add sound for transition
> Update map fishTank for game

- .idea/misc.xml
- src/main/AssetSetter.java
- src/main/GamePanel.java
- src/main/Main.java
- src/object/Fishing_Rod.java
Display fish that player has in inventory to the fishTank
> Add fish for fishTank. Fix the bug that draw animal at the right corner when restart the game

- src/main/EventHandler.java
Debug when player have more than 5 coin and affordable to buy grass but also die
> Fixing bug of restart function
